FROM node:22-alpine
WORKDIR /app
RUN apk update && apk add --no-cache openssl
COPY package*.json ./
RUN npm ci
RUN npm install -g nodemon
COPY prisma ./prisma/
COPY . .
RUN npx prisma generate
RUN npx prisma validate
EXPOSE 5555
CMD ["sh", "-c", "npx prisma migrate deploy && npm run db:studio & npm run dev"]
