services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - api-network
      - app-network

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - api-network

networks:
  app-network:
    driver: bridge
  api-network:
    driver: bridge

volumes:
  db-data:
