services:
  ui:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - 80:80
    networks:
      - api-network
      - app-network

  api:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - api-network
      - app-network

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - api-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
  api-network:
    driver: bridge

volumes:
  db-data:
